#
# Run pre-commit hooks. You can run them without installing
#  the hook with
#
# $ pre-commit run --all-files
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Run pre-commit hooks. You can run them without installing
#  the hook with
#
# $ pre-commit run --all-files
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: '(dag_pipeline_tools/(?!models/_generated).*|tests/(?!assets/).*)'
repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.25
    hooks:
      - id: helmlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '(chart)/.*'
      - id: check-yaml
        exclude: '(chart)/.*'
        args: [ --allow-multiple-documents ]
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
  - repo: local
    hooks:
      - id: fix-groovy-script
        name: Fix Groovy script
        entry:
          sh -c 'docker run --rm -u "$(id -u):$(id -g)"
          -w=/tmp -v "${PWD}":/tmp nvuillam/npm-groovy-lint
          --failon warning --verbose --fix'
        language: system
        files: Jenkinsfile|.*groovy$
  - repo: https://github.com/koxudaxi/datamodel-code-generator/
    rev: 0.28.1
    hooks:
      - id: datamodel-code-generator
        additional_dependencies: ["datamodel-code-generator[http]"]
        files: dag_pipeline_tools/data/schemas/.*
  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: 'v1.3.0'
  #  hooks:
  #    - additional_dependencies:
  #      - types-PyYAML
  #      - types-requests
  #      - types-retry
  #      id: mypy